config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Inustagram</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <script src="https://kit.fontawesome.com/12cd32fff0.js" crossorigin="anonymous"></script>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

  <%# Header %>
  <nav class="navbar navbar-light bg-light">
    <div class="container d-flex">
      <div class="logo">
        <a href="#" class="navbar-brand">
          <%= fa_stacked_icon "paw", base:"square-o" %>
          <span class="logo-name">INUstagram</span>
        </a>
      </div>

      <div class="d-none d-sm-inline m-auto">
        <form class="form-inline md-form form-sm mt-0 search-form">
          <%=fa_icon "search"%>
          <input class="form-control form-control-sm ml-3 w-75" type="text" placeholder="@Search" aria-label="Search">
        </form>

      </div>
      <div class="user-section">
        <a href=""><i class="far fa-compass"></i></a>
        <a href=""><i class="far fa-heart"></i></a>
        <% if user_signed_in? %>
          <a href="<%= user_path(current_user) %>"><i class="far fa-user"></i></a>
        <% else %>
          <a href="<%= new_user_session_path %>"><i class="far fa-sign-in"></i></a>
        <% end %>
      </div>

    </div>
  </nav>

  <%# Main-contet %>
  <main class="container" style="min-height: 500px;">
  <p class="notice"><%= notice %></p> 
    <p class="alert"><%= alert %></p>
    <p class="notice"><%= notice %></p> 
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </main>


  <%# Footer %>
  <footer class="container footer d-flex">
    <p>&copy; 2019 INUstagram</p>
  </footer>
</body>

</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>